### ISSUE TITLE
installed, but does not take the data already exists

### ISSUE THREAD

**Issue by Tobias-Conrad** [PiwikPRO/plugin-AdvancedCampaignReporting#14]
i done a lot of google campain links which are shown in ecommerce/campains.
but not in your new AdvancedCampaignReporting view.

may get this data.

**Comment by mattab** [comment]
Hi @Tobias-Conrad 
The data should show up after you activate the AdvancedCampaignReporting plugin (for future data after plugin was activated).

**Comment by kevinoid** [comment]
Thanks for writing/maintaining this plugin!

I just ran across this behavior as well and found it a bit confusing.  Specifically, the site had existing campaign data and after installing ACR the data now shows up in some places (such as Referrers > All Referrers under Referrer Type - Campaign) but not in Referrers > Campaigns (presumably because that now only shows ACR data).

So the old data doesn't appear to be completely lost, just not compatible with the ACR features, correct?  If ACR is removed, will the limited campaign information available in Piwik by default be recorded for the visits during the time ACR is installed?  Is there any possibility of migrating old campaign data into ACR?  Perhaps a note clarifying how data is handled in the README could avoid this confusion for others.

**Comment by mattab** [comment]
Hi @kevinoid 

> So the old data doesn't appear to be completely lost, just not compatible with the ACR features, correct?

correct

> If ACR is removed, will the limited campaign information available in Piwik by default be recorded for the visits during the time ACR is installed?

Yes, it should work this way

>  Is there any possibility of migrating old campaign data into ACR?

Not yet possible - can you please create a new issue for this request?

**Comment by kevinoid** [comment]
Thanks @mattab!  That makes sense.  I've created #18 to track the issue.
